apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zsqr0jpwd-python 
  janus-idp.io/tekton: zsqr0jpwd-python
  backstage.io/kubernetes-id: zsqr0jpwd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zsqr0jpwd-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml