apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zsqr0jpwd-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:c65a956f61e7198d9cfdfded07d2b9f326b1414e@sha256:6c7865edb740c4e552088840b0fc213904c9bcd038f74d7baa3acf55d85ca220
          name: container-image
