apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zsqr0jpwd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zsqr0jpwd-python 
  name: zsqr0jpwd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zsqr0jpwd-python 
